### ISSUE TITLE
Use Test Binary | Help Wanted

### ISSUE THREAD

**Issue by MateusAmin** [dmikusa/rust-cnb#1]
I would like to run integration tests for a library independently from my application bin. To do so I need it deployed to my cluster. Hence, I was interested in using rust-cnb to create test image from my library's rust test binary. Is this possible?

**Comment by MateusAmin** [comment]
Doesn't look straight forward to find the binary itself but also not very difficult:

https://github.com/rust-lang/cargo/issues/5758

**Comment by MateusAmin** [comment]
I suppose I could just add a "test" bin to my library for the time being so not a blocker.

**Comment by dmikusa** [comment]
Happy to help see if we can make this work. I'm not 100% I follow on what you're trying to do though. 

A few questions...

1. What do you normally do to run your tests locally? or in your current setup?
2. When would you want the tests to run? It sounds like you'd not want them to run when you execute `pack build` to run the CNBs, but later. Like you'd want your tests to be included into your generated image. Is that correct?
3. Are you trying to produce two different images, like one to run your tests and one to run your actual app? or is there no actual app, since you just mentioned trying to test a library?

Thanks for clarifying!

**Comment by dmikusa** [comment]
If you have a little test app/lib you could link me to so I could play around with trying to get it to work, that would be incredibly helpful as well.

**Comment by MateusAmin** [comment]
Let me see what I can do. Thanks for reading!

**Comment by dmikusa** [comment]
@MateusAmin - How are things going with this?
